# Generated by Django 5.0.3 on 2024-04-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_video_name_video_title_alter_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=''),
        ),
    ]
