# Generated by Django 5.0.3 on 2024-04-16 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_post_short_url_alter_video_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(
                blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(
                blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
