# Generated by Django 5.0.3 on 2024-04-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_comment'),
        ('app', '0014_post_dislikes_count_post_likes_count'),
    ]

    operations = [
    ]
