FROM python:3.12.2

WORKDIR /VideoBase

RUN pip install django
RUN pip install django-graphql-jwt
RUN pip install graphene
RUN pip install graphene_django
RUN pip install jinja2
RUN pip install django-cors-headers
RUN pip install psycopg2
RUN pip install djangorestframework
RUN pip install rest_framework
RUN pip install firebase-admin
RUN pip install grpahene_file_upload
RUN pip install autopep8


COPY . .

ENV DJANGO_SETTINGS_MODULE=VideoBase.settings

CMD ["python", "manage.py", "runserver"]
